# action.yml

name: 'Compilation'
description: 'Compiles source files'
inputs:
  gcc-url:
    description: 'URL to download the arm-none-eabi-gcc compiler'
    required: false
    default: 'https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2?rev=78196d3461ba4c9089a67b5f33edf82a&hash=D484B37FF37D6FC3597EBE2877FB666A41D5253B'
  stm32-series:
    description: 'Identifier of the STM32 series whose sources are to be compiled (e.g. F4, G0, H7)'
    required: true
  option-list:
    description: 'List of option (-m) to pass as arguments to the GCC command'
    required: true
outputs:
  compile-result: # id of output
    description: 'File name of the compile result'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gcc-url }}
    - ${{ inputs.stm32-series }}
    - ${{ inputs.option-list }}
